CREATE TABLE `order`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
    `pid` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '产品ID',
    `amount` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单金额',
    `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '订单状态',
    `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    KEY `idx_uid`(`uid`),
    KEY `idx_pid`(`pid`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;